# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'github-runner-vm-runner-group-mi' #Add Docker Service Connection
  imageRepository: 'samplewebapp'   #This is image repo you can keep it
  containerRegistry: 'k8internalacr.azurecr.io' #Add Container Registry login server
  dockerfilePath: '**/Dockerfile' #It is already there
  tag: '$(Build.BuildId)' #It is already there
  imagePullSecret: 'k8internalacr' #'Try to add as per acr'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    # - task: Docker@2
    #   displayName: Build and push an image to Azure container registry
    #   inputs:
    #     command: buildAndPush
    #     repository: $(imageRepository)
    #     dockerfile: $(dockerfilePath)
    #     containerRegistry: $(dockerRegistryServiceConnection)
    #     tags: |
    #       $(tag)

    - task: Docker@2
      displayName: 'Build Docker Image and Push to ACR'
      inputs:
        containerRegistry: 'CPG-ACR-SC'
        repository: 'app-matrix'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'manifests/'
        Contents: '**/*.yml'
        TargetFolder: '$(Pipeline.Workspace)/manifests'
    
    - task: PublishPipelineArtifact@1
      inputs:
       targetPath: '$(Pipeline.Workspace)/manifests'
       artifact: 'manifests'
       publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy AKS Image to Dev Env
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'env'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@1
            displayName: Create imagePullSecret
            inputs:
              action: 'createSecret'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'Visual Studio Enterprise Subscription – MPN (0f87b7f3-b8ff-4c25-b09a-901f6869202e)'
              azureResourceGroup: 'god-father-aks-app-demo'
              kubernetesCluster: 'god-father-aks-app-cluster'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: 'godfatheraksappacr'  #'$(imagePullSecret)'
              dockerRegistryEndpoint: 'CPG-ACR-SC'

          - task: KubernetesManifest@1
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: 'deploy'
              connectionType: 'azureResourceManager'
              azureSubscriptionConnection: 'Visual Studio Enterprise Subscription – MPN (0f87b7f3-b8ff-4c25-b09a-901f6869202e)'
              azureResourceGroup: 'god-father-aks-app-demo'
              kubernetesCluster: 'god-father-aks-app-cluster'
              namespace: 'default'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yml
                $(Pipeline.Workspace)/manifests/service.yml
              containers: 'godfatheraksappacr.azurecr.io/app-matrix:$(Build.BuildId)'
              imagePullSecrets: 'godfatheraksappacr'

