apiVersion : apps/v1
kind: Deployment
metadata:
  name: app-matrix 
spec:
  replicas: 25
  selector:
    matchLabels:
      app: app-matrix
  template:
    metadata:
      labels:
        app: app-matrix 
    spec:
      containers:
        - name: app-matrix 
          image: godfatheraksappacr.azurecr.io/app-matrix
          ports:
          - containerPort: 80